drop extension if exists "pg_net";


  create table "public"."match_scores" (
    "id" bigint generated by default as identity not null,
    "match_id" bigint,
    "player1_score" integer not null,
    "player2_score" integer not null,
    "winner_id" bigint,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."match_scores" enable row level security;


  create table "public"."matches" (
    "id" bigint generated by default as identity not null,
    "player1_id" bigint,
    "player2_id" bigint,
    "match_date" timestamp with time zone default now(),
    "status" text default 'completed'::text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."matches" enable row level security;


  create table "public"."profiles" (
    "id" bigint generated by default as identity not null,
    "country_code" text default '+91'::text,
    "mobile" text not null,
    "address" text,
    "name" text not null,
    "skill_level" text,
    "created_at" timestamp with time zone default now(),
    "auth_user_id" uuid
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX match_scores_pkey ON public.match_scores USING btree (id);

CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id);

CREATE UNIQUE INDEX one_score_per_match ON public.match_scores USING btree (match_id);

CREATE UNIQUE INDEX profiles_auth_user_id_unique ON public.profiles USING btree (auth_user_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."match_scores" add constraint "match_scores_pkey" PRIMARY KEY using index "match_scores_pkey";

alter table "public"."matches" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."match_scores" add constraint "match_scores_match_id_fkey" FOREIGN KEY (match_id) REFERENCES public.matches(id) not valid;

alter table "public"."match_scores" validate constraint "match_scores_match_id_fkey";

alter table "public"."match_scores" add constraint "match_scores_winner_id_fkey" FOREIGN KEY (winner_id) REFERENCES public.profiles(id) not valid;

alter table "public"."match_scores" validate constraint "match_scores_winner_id_fkey";

alter table "public"."match_scores" add constraint "one_score_per_match" UNIQUE using index "one_score_per_match";

alter table "public"."matches" add constraint "matches_player1_id_fkey" FOREIGN KEY (player1_id) REFERENCES public.profiles(id) not valid;

alter table "public"."matches" validate constraint "matches_player1_id_fkey";

alter table "public"."matches" add constraint "matches_player2_id_fkey" FOREIGN KEY (player2_id) REFERENCES public.profiles(id) not valid;

alter table "public"."matches" validate constraint "matches_player2_id_fkey";

alter table "public"."matches" add constraint "players_must_be_different" CHECK ((player1_id <> player2_id)) not valid;

alter table "public"."matches" validate constraint "players_must_be_different";

alter table "public"."profiles" add constraint "profiles_auth_user_id_fkey" FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_auth_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_auth_user_id_unique" UNIQUE using index "profiles_auth_user_id_unique";

set check_function_bodies = off;

create or replace view "public"."player_rankings" as  SELECT p.id,
    p.name,
    p.skill_level,
    count(ms.id) AS total_matches,
    count(ms.id) FILTER (WHERE (ms.winner_id = p.id)) AS wins,
    count(ms.id) FILTER (WHERE ((ms.id IS NOT NULL) AND (ms.winner_id <> p.id))) AS losses,
    (count(ms.id) FILTER (WHERE (ms.winner_id = p.id)) * 3) AS points
   FROM ((public.profiles p
     LEFT JOIN public.matches m ON (((p.id = m.player1_id) OR (p.id = m.player2_id))))
     LEFT JOIN public.match_scores ms ON ((ms.match_id = m.id)))
  GROUP BY p.id, p.name, p.skill_level
  ORDER BY (count(ms.id) FILTER (WHERE (ms.winner_id = p.id)) * 3) DESC, (count(ms.id) FILTER (WHERE (ms.winner_id = p.id))) DESC;


CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_match_score_winner()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  v_player1_id bigint;
  v_player2_id bigint;
begin
  select player1_id, player2_id
  into v_player1_id, v_player2_id
  from public.matches
  where id = new.match_id;

  if new.winner_id not in (v_player1_id, v_player2_id) then
    raise exception 'winner_id must be either player1_id or player2_id for this match';
  end if;

  return new;
end;
$function$
;

grant delete on table "public"."match_scores" to "anon";

grant insert on table "public"."match_scores" to "anon";

grant references on table "public"."match_scores" to "anon";

grant select on table "public"."match_scores" to "anon";

grant trigger on table "public"."match_scores" to "anon";

grant truncate on table "public"."match_scores" to "anon";

grant update on table "public"."match_scores" to "anon";

grant delete on table "public"."match_scores" to "authenticated";

grant insert on table "public"."match_scores" to "authenticated";

grant references on table "public"."match_scores" to "authenticated";

grant select on table "public"."match_scores" to "authenticated";

grant trigger on table "public"."match_scores" to "authenticated";

grant truncate on table "public"."match_scores" to "authenticated";

grant update on table "public"."match_scores" to "authenticated";

grant delete on table "public"."match_scores" to "service_role";

grant insert on table "public"."match_scores" to "service_role";

grant references on table "public"."match_scores" to "service_role";

grant select on table "public"."match_scores" to "service_role";

grant trigger on table "public"."match_scores" to "service_role";

grant truncate on table "public"."match_scores" to "service_role";

grant update on table "public"."match_scores" to "service_role";

grant delete on table "public"."matches" to "anon";

grant insert on table "public"."matches" to "anon";

grant references on table "public"."matches" to "anon";

grant select on table "public"."matches" to "anon";

grant trigger on table "public"."matches" to "anon";

grant truncate on table "public"."matches" to "anon";

grant update on table "public"."matches" to "anon";

grant delete on table "public"."matches" to "authenticated";

grant insert on table "public"."matches" to "authenticated";

grant references on table "public"."matches" to "authenticated";

grant select on table "public"."matches" to "authenticated";

grant trigger on table "public"."matches" to "authenticated";

grant truncate on table "public"."matches" to "authenticated";

grant update on table "public"."matches" to "authenticated";

grant delete on table "public"."matches" to "service_role";

grant insert on table "public"."matches" to "service_role";

grant references on table "public"."matches" to "service_role";

grant select on table "public"."matches" to "service_role";

grant trigger on table "public"."matches" to "service_role";

grant truncate on table "public"."matches" to "service_role";

grant update on table "public"."matches" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Users can read scores of own matches"
  on "public"."match_scores"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.matches m
     JOIN public.profiles p ON (((p.id = m.player1_id) OR (p.id = m.player2_id))))
  WHERE ((m.id = match_scores.match_id) AND (p.auth_user_id = auth.uid())))));



  create policy "Users can submit scores for own matches"
  on "public"."match_scores"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM (public.matches m
     JOIN public.profiles p ON (((p.id = m.player1_id) OR (p.id = m.player2_id))))
  WHERE ((m.id = match_scores.match_id) AND (p.auth_user_id = auth.uid())))));



  create policy "Users can read own matches"
  on "public"."matches"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles p
  WHERE ((p.auth_user_id = auth.uid()) AND ((p.id = matches.player1_id) OR (p.id = matches.player2_id))))));



  create policy "Users can read own profile"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((auth.uid() = auth_user_id));



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = auth_user_id))
with check ((auth.uid() = auth_user_id));


CREATE TRIGGER check_match_score_winner BEFORE INSERT OR UPDATE ON public.match_scores FOR EACH ROW EXECUTE FUNCTION public.validate_match_score_winner();


