create table if not exists public.app_roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamp with time zone not null default now(),
  constraint app_roles_name_check check (name in ('admin', 'player', 'coach'))
);

alter table public.app_roles enable row level security;

create table if not exists public.profile_roles (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  role_id bigint not null references public.app_roles(id) on delete cascade,
  assigned_by_profile_id bigint references public.profiles(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  constraint profile_roles_profile_role_unique unique (profile_id, role_id)
);

alter table public.profile_roles enable row level security;

create table if not exists public.coach_player_assignments (
  id bigint generated by default as identity primary key,
  coach_profile_id bigint not null references public.profiles(id) on delete cascade,
  player_profile_id bigint not null references public.profiles(id) on delete cascade,
  assigned_by_profile_id bigint references public.profiles(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone,
  constraint coach_player_assignments_not_self_check check (coach_profile_id <> player_profile_id),
  constraint coach_player_assignments_active_ended_check check (
    (is_active = true and ended_at is null)
    or (is_active = false)
  )
);

alter table public.coach_player_assignments enable row level security;

create unique index if not exists coach_player_assignments_active_unique
  on public.coach_player_assignments (coach_profile_id, player_profile_id)
  where is_active = true;

create index if not exists profile_roles_profile_id_idx
  on public.profile_roles (profile_id);

create index if not exists profile_roles_role_id_idx
  on public.profile_roles (role_id);

create index if not exists coach_player_assignments_coach_profile_id_idx
  on public.coach_player_assignments (coach_profile_id)
  where is_active = true;

create index if not exists coach_player_assignments_player_profile_id_idx
  on public.coach_player_assignments (player_profile_id)
  where is_active = true;

insert into public.app_roles (name, description)
values
  ('admin', 'Can manage members, matches, scores, roles, assignments, and skill ladder data.'),
  ('player', 'Can manage their own member profile, matches, media, and skill progress.'),
  ('coach', 'Can review and comment on assigned players skill progress and media.')
on conflict (name) do update
set description = excluded.description;

insert into public.profile_roles (profile_id, role_id)
select p.id, ar.id
from public.profiles p
cross join public.app_roles ar
where ar.name = 'player'
on conflict (profile_id, role_id) do nothing;

create or replace function public.assign_default_player_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
declare
  player_role_id bigint;
begin
  select id into player_role_id
  from public.app_roles
  where name = 'player';

  if player_role_id is not null then
    insert into public.profile_roles (profile_id, role_id)
    values (new.id, player_role_id)
    on conflict (profile_id, role_id) do nothing;
  end if;

  return new;
end;
$function$;

drop trigger if exists assign_default_player_role_on_profile_insert on public.profiles;

create trigger assign_default_player_role_on_profile_insert
after insert on public.profiles
for each row execute function public.assign_default_player_role();

create or replace function public.current_profile_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $function$
  select p.id
  from public.profiles p
  where p.auth_user_id = auth.uid()
  limit 1;
$function$;

create or replace function public.has_role(role_name text)
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select exists (
    select 1
    from public.profile_roles pr
    join public.app_roles ar on ar.id = pr.role_id
    join public.profiles p on p.id = pr.profile_id
    where p.auth_user_id = auth.uid()
      and ar.name = role_name
  );
$function$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select public.has_role('admin');
$function$;

create or replace function public.is_coach_for_player(player_profile_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select exists (
    select 1
    from public.coach_player_assignments cpa
    join public.profiles coach_profile on coach_profile.id = cpa.coach_profile_id
    where coach_profile.auth_user_id = auth.uid()
      and cpa.player_profile_id = is_coach_for_player.player_profile_id
      and cpa.is_active = true
      and cpa.ended_at is null
  );
$function$;

grant execute on function public.current_profile_id() to authenticated;
grant execute on function public.has_role(text) to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_coach_for_player(bigint) to authenticated;

grant select on table public.app_roles to authenticated;
grant insert, update, delete on table public.app_roles to authenticated;
grant select on table public.profile_roles to authenticated;
grant insert, update, delete on table public.profile_roles to authenticated;
grant select on table public.coach_player_assignments to authenticated;
grant insert, update, delete on table public.coach_player_assignments to authenticated;

grant select, insert, update, delete on table public.app_roles to service_role;
grant select, insert, update, delete on table public.profile_roles to service_role;
grant select, insert, update, delete on table public.coach_player_assignments to service_role;

create policy "Authenticated users can read role names"
on public.app_roles
as permissive
for select
to authenticated
using (true);

create policy "Admins can manage role names"
on public.app_roles
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Users can read own roles"
on public.profile_roles
as permissive
for select
to authenticated
using (
  profile_id = public.current_profile_id()
  or public.is_admin()
);

create policy "Admins can manage profile roles"
on public.profile_roles
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Coaches can read own assignments"
on public.coach_player_assignments
as permissive
for select
to authenticated
using (
  public.is_admin()
  or coach_profile_id = public.current_profile_id()
  or player_profile_id = public.current_profile_id()
);

create policy "Admins can manage coach assignments"
on public.coach_player_assignments
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage all profiles"
on public.profiles
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Coaches can read assigned player profiles"
on public.profiles
as permissive
for select
to authenticated
using (public.is_coach_for_player(id));

create policy "Admins can read all matches"
on public.matches
as permissive
for select
to authenticated
using (public.is_admin());

create policy "Admins can manage all matches"
on public.matches
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can read all match scores"
on public.match_scores
as permissive
for select
to authenticated
using (public.is_admin());

create policy "Admins can manage all match scores"
on public.match_scores
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins and assigned coaches can read skill progress"
on public.member_skill_progress
as permissive
for select
to authenticated
using (
  public.is_admin()
  or public.is_coach_for_player(profile_id)
);

create policy "Admins can manage all skill progress"
on public.member_skill_progress
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins and assigned coaches can read skill media links"
on public.member_skill_media
as permissive
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.member_skill_progress msp
    where msp.id = member_skill_media.progress_id
      and public.is_coach_for_player(msp.profile_id)
  )
);

create policy "Admins can manage all skill media links"
on public.member_skill_media
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins and assigned coaches can read skill comment links"
on public.member_skill_comments
as permissive
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.member_skill_progress msp
    where msp.id = member_skill_comments.progress_id
      and public.is_coach_for_player(msp.profile_id)
  )
);

create policy "Assigned coaches can create skill comment links"
on public.member_skill_comments
as permissive
for insert
to authenticated
with check (
  public.is_admin()
  or exists (
    select 1
    from public.member_skill_progress msp
    join public.comments c on c.id = member_skill_comments.comment_id
    where msp.id = member_skill_comments.progress_id
      and c.profile_id = public.current_profile_id()
      and public.is_coach_for_player(msp.profile_id)
  )
);

create policy "Admins can manage all skill comment links"
on public.member_skill_comments
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins and assigned coaches can read related comments"
on public.comments
as permissive
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.member_skill_comments msc
    join public.member_skill_progress msp on msp.id = msc.progress_id
    where msc.comment_id = comments.id
      and public.is_coach_for_player(msp.profile_id)
  )
);

create policy "Assigned coaches can create own comments"
on public.comments
as permissive
for insert
to authenticated
with check (
  profile_id = public.current_profile_id()
  and public.has_role('coach')
);

create policy "Admins can manage all comments"
on public.comments
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins and assigned coaches can read related media"
on public.media
as permissive
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.member_skill_media msm
    join public.member_skill_progress msp on msp.id = msm.progress_id
    where msm.media_id = media.id
      and public.is_coach_for_player(msp.profile_id)
  )
);

create policy "Admins can manage all media"
on public.media
as permissive
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

comment on table public.app_roles is 'Application role names such as admin, player, and coach.';
comment on table public.profile_roles is 'Many-to-many role assignment for profiles. A person can be admin, player, coach, or multiple roles.';
comment on table public.coach_player_assignments is 'Active relationship that lets coaches review assigned player skill progress and media.';
