insert into public.skill_categories (
  name,
  description,
  sort_order,
  metadata
)
values
  (
    'Foundation & Movement',
    'Core body position, balance, recovery, and movement skills that support every shot.',
    10,
    '{"icon":"footprints"}'::jsonb
  ),
  (
    'Forehand',
    'Forehand control, attack, placement, and transition skills.',
    20,
    '{"icon":"activity"}'::jsonb
  ),
  (
    'Backhand',
    'Backhand control, attack, blocks, flicks, and transitions.',
    30,
    '{"icon":"activity"}'::jsonb
  ),
  (
    'Push & Short Game',
    'Touch, push, low-ball control, and over-the-table decision making.',
    40,
    '{"icon":"move-horizontal"}'::jsonb
  ),
  (
    'Serve',
    'Serve legality, spin, placement, disguise, and third-ball setup skills.',
    50,
    '{"icon":"send"}'::jsonb
  ),
  (
    'Receive',
    'Reading serves and choosing safe, neutralizing, or attacking receive options.',
    60,
    '{"icon":"corner-down-left"}'::jsonb
  ),
  (
    'Spin Understanding',
    'Reading, creating, varying, and adapting to spin.',
    70,
    '{"icon":"refresh-cw"}'::jsonb
  ),
  (
    'Rally Control',
    'Consistency, placement, tempo, direction changes, and controlled exchanges.',
    80,
    '{"icon":"repeat"}'::jsonb
  ),
  (
    'Attack & Point Construction',
    'Opening attacks, attacking choices, finishing points, and building patterns.',
    90,
    '{"icon":"zap"}'::jsonb
  ),
  (
    'Defense',
    'Blocking, lobbing, fishing, absorbing pressure, and turning defense into attack.',
    100,
    '{"icon":"shield"}'::jsonb
  ),
  (
    'Match Strategy',
    'Opponent analysis, tactical adaptation, score awareness, and pattern selection.',
    110,
    '{"icon":"map"}'::jsonb
  ),
  (
    'Mental Game',
    'Focus, confidence, routines, pressure handling, and competitive resilience.',
    120,
    '{"icon":"brain"}'::jsonb
  ),
  (
    'Fitness & Physical Readiness',
    'Warm-up, mobility, strength, agility, endurance, recovery, and injury prevention.',
    130,
    '{"icon":"heart-pulse"}'::jsonb
  );

insert into public.skills (
  category_id,
  name,
  description,
  difficulty_level,
  sort_order
)
select
  sc.id,
  seeded.skill_name,
  seeded.skill_description,
  seeded.difficulty_level,
  seeded.sort_order
from (
  values
    ('Foundation & Movement', 'Ready position', 'Build a balanced, repeatable ready position before every shot.', 1, 10),
    ('Foundation & Movement', 'Grip correctness', 'Maintain a relaxed, stable grip that allows forehand and backhand freedom.', 1, 20),
    ('Foundation & Movement', 'Basic stance and balance', 'Stay low, centered, and balanced through contact and recovery.', 1, 30),
    ('Foundation & Movement', 'Side-to-side footwork', 'Move laterally without crossing feet or losing balance.', 2, 40),
    ('Foundation & Movement', 'In-and-out footwork', 'Move forward for short balls and recover for deeper balls.', 2, 50),
    ('Foundation & Movement', 'Recovery after each shot', 'Return to a neutral position quickly after every stroke.', 2, 60),
    ('Foundation & Movement', 'Weight transfer', 'Coordinate legs, hips, and trunk to transfer weight through the ball.', 2, 70),
    ('Foundation & Movement', 'Timing and contact point', 'Contact the ball at a consistent height and distance from the body.', 2, 80),
    ('Foundation & Movement', 'Reading ball height, speed, and spin', 'Identify the incoming ball early enough to choose the correct response.', 3, 90),
    ('Foundation & Movement', 'Rally consistency base', 'Keep controlled rallies going with repeatable technique and recovery.', 2, 100),

    ('Forehand', 'Forehand drive', 'Execute a compact, controlled forehand drive with stable contact.', 1, 10),
    ('Forehand', 'Forehand counter-hit', 'Counter incoming pace with a controlled forward stroke.', 2, 20),
    ('Forehand', 'Forehand topspin against block', 'Loop or topspin a blocked ball with shape and recovery.', 3, 30),
    ('Forehand', 'Forehand topspin against backspin', 'Open safely and effectively against backspin balls.', 3, 40),
    ('Forehand', 'Forehand loop', 'Produce a spin-focused attacking forehand with full-body coordination.', 3, 50),
    ('Forehand', 'Forehand smash', 'Finish high or weak balls with a decisive flat attack.', 2, 60),
    ('Forehand', 'Forehand flick', 'Attack short balls over the table with a compact forehand action.', 3, 70),
    ('Forehand', 'Forehand block', 'Absorb pace on the forehand side with controlled placement.', 2, 80),
    ('Forehand', 'Forehand counter-loop', 'Counter an opponent topspin with timing, spin, and balance.', 5, 90),
    ('Forehand', 'Forehand kill on high ball', 'Finish high balls reliably without over-hitting.', 3, 100),
    ('Forehand', 'Forehand from middle/body', 'Use forehand effectively when the ball comes into the elbow or middle.', 3, 110),
    ('Forehand', 'Forehand down-the-line placement', 'Control forehand direction down the line under rally pressure.', 3, 120),
    ('Forehand', 'Forehand cross-court placement', 'Control forehand angle and depth cross-court.', 2, 130),

    ('Backhand', 'Backhand drive', 'Execute a compact, controlled backhand drive with stable contact.', 1, 10),
    ('Backhand', 'Backhand counter-hit', 'Counter incoming pace with a short, balanced backhand stroke.', 2, 20),
    ('Backhand', 'Backhand topspin against block', 'Topspin blocked balls from the backhand side with control.', 3, 30),
    ('Backhand', 'Backhand topspin against backspin', 'Open against backspin using backhand topspin.', 4, 40),
    ('Backhand', 'Backhand loop', 'Produce a stronger spin-based backhand attack.', 4, 50),
    ('Backhand', 'Backhand punch block', 'Redirect pace with a firmer, more active backhand block.', 3, 60),
    ('Backhand', 'Backhand active block', 'Add pressure while blocking by taking the ball early.', 3, 70),
    ('Backhand', 'Backhand flick', 'Attack short balls over the table with a compact backhand action.', 3, 80),
    ('Backhand', 'Banana flick', 'Use sidespin/topspin wrist action to attack short serves or pushes.', 5, 90),
    ('Backhand', 'Backhand smash', 'Finish high balls from the backhand side.', 3, 100),
    ('Backhand', 'Backhand placement control', 'Place backhand balls to wide angles and middle targets.', 3, 110),
    ('Backhand', 'Backhand-to-forehand transition', 'Move smoothly from backhand contact into forehand readiness.', 3, 120),
    ('Backhand', 'Backhand from wide angle', 'Recover and control balls from the wide backhand corner.', 4, 130),

    ('Push & Short Game', 'Forehand push', 'Return backspin safely from the forehand side.', 1, 10),
    ('Push & Short Game', 'Backhand push', 'Return backspin safely from the backhand side.', 1, 20),
    ('Push & Short Game', 'Heavy backspin push', 'Create heavier backspin while keeping the ball low.', 3, 30),
    ('Push & Short Game', 'Fast long push', 'Push deep and fast to pressure the opponent.', 2, 40),
    ('Push & Short Game', 'Short touch', 'Keep short balls short with soft hands and low trajectory.', 3, 50),
    ('Push & Short Game', 'Drop shot', 'Use soft touch to bring the ball very short after a deeper exchange.', 4, 60),
    ('Push & Short Game', 'Push to wide forehand', 'Place pushes wide to the opponent forehand.', 2, 70),
    ('Push & Short Game', 'Push to wide backhand', 'Place pushes wide to the opponent backhand.', 2, 80),
    ('Push & Short Game', 'Push to middle/elbow', 'Use push placement to jam the opponent decision point.', 3, 90),
    ('Push & Short Game', 'Short vs long ball recognition', 'Judge whether a ball can be attacked or must be played short.', 3, 100),
    ('Push & Short Game', 'Low net clearance control', 'Keep short-game balls low over the net.', 3, 110),
    ('Push & Short Game', 'Spin variation on push', 'Vary heavy, light, and no-spin pushes with similar motion.', 4, 120),

    ('Serve', 'Legal serve action', 'Serve with visible ball, legal toss, and clear contact rules.', 1, 10),
    ('Serve', 'Pendulum serve', 'Use a forehand pendulum motion to create sidespin variations.', 2, 20),
    ('Serve', 'Reverse pendulum serve', 'Use reverse sidespin from a forehand service action.', 4, 30),
    ('Serve', 'Backhand serve', 'Serve using backhand action with spin and placement options.', 2, 40),
    ('Serve', 'Tomahawk serve', 'Use tomahawk action to create awkward sidespin and placement.', 4, 50),
    ('Serve', 'Hook serve', 'Use hook action to vary spin and disguise.', 4, 60),
    ('Serve', 'Fast long serve', 'Serve deep and fast to surprise or pressure the receiver.', 2, 70),
    ('Serve', 'Short backspin serve', 'Serve short with reliable backspin and low bounce.', 2, 80),
    ('Serve', 'Short sidespin serve', 'Serve short with sidespin while keeping the ball low.', 3, 90),
    ('Serve', 'No-spin serve', 'Disguise low-spin serves using a similar motion to spin serves.', 3, 100),
    ('Serve', 'Topspin serve', 'Serve with topspin or side-topspin to force pop-ups or timing errors.', 3, 110),
    ('Serve', 'Half-long serve', 'Serve near the end line to create hesitation.', 4, 120),
    ('Serve', 'Serve placement short forehand', 'Place short serves accurately to the forehand side.', 2, 130),
    ('Serve', 'Serve placement short backhand', 'Place short serves accurately to the backhand side.', 2, 140),
    ('Serve', 'Serve placement wide angles', 'Use wide placements to stretch the receiver.', 3, 150),
    ('Serve', 'Serve placement body/elbow', 'Serve into the receiver decision point.', 3, 160),
    ('Serve', 'Same motion, different spin', 'Produce different spins with similar preparation and contact disguise.', 4, 170),
    ('Serve', 'Serve disguise', 'Hide intention through rhythm, contact quality, and similar motions while staying legal.', 5, 180),
    ('Serve', 'Third-ball attack setup', 'Serve with a clear plan for the expected return.', 4, 190),
    ('Serve', 'Serve routine and consistency', 'Repeat a reliable serve routine under match pressure.', 2, 200),

    ('Receive', 'Read backspin serve', 'Recognize and respond to backspin serves.', 2, 10),
    ('Receive', 'Read topspin serve', 'Recognize and respond to topspin or side-topspin serves.', 2, 20),
    ('Receive', 'Read sidespin serve', 'Identify sidespin direction from motion, flight, and bounce.', 3, 30),
    ('Receive', 'Read no-spin serve', 'Identify low-spin serves and avoid over-adjusting.', 3, 40),
    ('Receive', 'Short push receive', 'Receive short serves safely with a low short push.', 2, 50),
    ('Receive', 'Long push receive', 'Push deep to neutralize or pressure serve advantage.', 2, 60),
    ('Receive', 'Flick receive', 'Attack suitable short serves with forehand or backhand flick.', 3, 70),
    ('Receive', 'Banana flick receive', 'Attack short serves with backhand banana flick.', 5, 80),
    ('Receive', 'Drop receive', 'Use soft touch to keep receive short.', 4, 90),
    ('Receive', 'Aggressive receive', 'Attack or pressure serves instead of only neutralizing.', 4, 100),
    ('Receive', 'Passive safe receive', 'Choose a safe receive when reading is uncertain.', 2, 110),
    ('Receive', 'Receive placement', 'Place receives to wide, short, deep, or middle targets deliberately.', 3, 120),
    ('Receive', 'Handle fast long serves', 'React to and attack or control fast long serves.', 3, 130),
    ('Receive', 'Handle heavy spin serves', 'Adjust bat angle and contact for heavy spin serves.', 4, 140),
    ('Receive', 'Neutralize opponent best serve', 'Develop a reliable plan against an opponent favorite serve.', 4, 150),

    ('Spin Understanding', 'Understand topspin', 'Know how topspin affects flight, bounce, and racket angle.', 1, 10),
    ('Spin Understanding', 'Understand backspin', 'Know how backspin affects flight, bounce, and racket angle.', 1, 20),
    ('Spin Understanding', 'Understand sidespin', 'Know how sidespin changes ball direction after bounce and contact.', 2, 30),
    ('Spin Understanding', 'Understand no-spin', 'Recognize and play low-spin balls correctly.', 2, 40),
    ('Spin Understanding', 'Create heavy spin', 'Use brushing contact and acceleration to create heavier spin.', 3, 50),
    ('Spin Understanding', 'Vary spin amount', 'Change spin without making the intention obvious.', 4, 60),
    ('Spin Understanding', 'Read spin from racket angle', 'Use opponent racket angle to predict spin.', 3, 70),
    ('Spin Understanding', 'Read spin from ball flight', 'Use curve, speed, and arc to predict spin.', 3, 80),
    ('Spin Understanding', 'Read spin from bounce', 'Use bounce behavior to confirm spin.', 3, 90),
    ('Spin Understanding', 'Adjust racket angle for spin', 'Change racket angle correctly for incoming spin.', 2, 100),
    ('Spin Understanding', 'Use spin to force weak returns', 'Create spin with a tactical purpose.', 4, 110),
    ('Spin Understanding', 'Combine speed and spin', 'Balance pace and spin for effective attacking balls.', 4, 120),

    ('Rally Control', '10-ball forehand consistency', 'Maintain ten controlled forehand balls in a row.', 1, 10),
    ('Rally Control', '20-ball forehand consistency', 'Maintain twenty controlled forehand balls in a row.', 2, 20),
    ('Rally Control', '10-ball backhand consistency', 'Maintain ten controlled backhand balls in a row.', 1, 30),
    ('Rally Control', '20-ball backhand consistency', 'Maintain twenty controlled backhand balls in a row.', 2, 40),
    ('Rally Control', 'Forehand-backhand alternating rally', 'Alternate forehand and backhand while maintaining rhythm and recovery.', 2, 50),
    ('Rally Control', 'Cross-court control', 'Rally cross-court with depth, timing, and direction control.', 2, 60),
    ('Rally Control', 'Down-the-line control', 'Change to or maintain down-the-line placement safely.', 3, 70),
    ('Rally Control', 'Middle placement control', 'Use the opponent elbow/middle as a consistent placement target.', 3, 80),
    ('Rally Control', 'Safe direction change', 'Change direction without losing balance or over-hitting.', 3, 90),
    ('Rally Control', 'Change pace', 'Vary rally speed to disturb opponent rhythm.', 3, 100),
    ('Rally Control', 'Control ball depth', 'Keep rally balls deep or short by intention.', 3, 110),
    ('Rally Control', 'Low-risk rally selection', 'Choose rally balls that reduce error while keeping pressure.', 3, 120),
    ('Rally Control', 'Reset during fast rallies', 'Recover control when the rally becomes too fast or chaotic.', 4, 130),

    ('Attack & Point Construction', 'Opening attack against backspin', 'Start attack safely against push or chop balls.', 3, 10),
    ('Attack & Point Construction', 'Third-ball attack', 'Attack the first predictable return after serve.', 3, 20),
    ('Attack & Point Construction', 'Fifth-ball attack', 'Build one more planned shot after the third-ball phase.', 4, 30),
    ('Attack & Point Construction', 'Attack weak pushes', 'Recognize and punish pushes that are high, long, or light.', 3, 40),
    ('Attack & Point Construction', 'Attack high balls', 'Finish high balls with the right amount of power and control.', 2, 50),
    ('Attack & Point Construction', 'Attack half-long balls', 'Recognize and attack balls that drift close to the end line.', 4, 60),
    ('Attack & Point Construction', 'Choose when to attack', 'Select attacking balls based on spin, height, depth, and balance.', 3, 70),
    ('Attack & Point Construction', 'Choose when to stay patient', 'Avoid forcing attacks from poor positions or poor reads.', 3, 80),
    ('Attack & Point Construction', 'Create openings with placement', 'Use placement to create a weaker next ball.', 4, 90),
    ('Attack & Point Construction', 'Use wide angles', 'Attack into wide spaces to stretch the opponent.', 4, 100),
    ('Attack & Point Construction', 'Target opponent elbow', 'Attack the transition point between forehand and backhand.', 3, 110),
    ('Attack & Point Construction', 'Finish points', 'Convert advantages into winning balls.', 3, 120),
    ('Attack & Point Construction', 'Recover after attack', 'Return to balance after attacking so the next ball is playable.', 3, 130),
    ('Attack & Point Construction', 'Spinny vs fast attack variation', 'Choose between spin-heavy and speed-heavy attacks based on the ball.', 4, 140),

    ('Defense', 'Passive block', 'Control incoming attacks by absorbing pace.', 2, 10),
    ('Defense', 'Active block', 'Redirect pace early and apply pressure while blocking.', 3, 20),
    ('Defense', 'Chop block', 'Use a chopping block action to change spin and tempo.', 5, 30),
    ('Defense', 'Lob', 'Return smashes or attacks with high defensive balls.', 3, 40),
    ('Defense', 'Fishing', 'Defend from distance with controlled topspin returns.', 4, 50),
    ('Defense', 'Counter-attack from defense', 'Turn a defensive position into an attacking opportunity.', 5, 60),
    ('Defense', 'Handle smashes', 'Survive and place returns against repeated smashes.', 4, 70),
    ('Defense', 'Handle fast topspin', 'Block or counter fast topspin safely.', 3, 80),
    ('Defense', 'Handle wide-angle attacks', 'Move and recover against balls played to extreme angles.', 4, 90),
    ('Defense', 'Stay balanced under pressure', 'Maintain posture and decision quality when defending.', 3, 100),
    ('Defense', 'Return one more ball', 'Extend points by making the opponent hit another quality shot.', 3, 110),
    ('Defense', 'Defensive placement', 'Defend to locations that reduce opponent attack quality.', 4, 120),
    ('Defense', 'Turn defense into attack', 'Identify the first safe ball to regain initiative.', 5, 130),

    ('Match Strategy', 'Identify opponent weakness', 'Observe and target technical or tactical weaknesses.', 3, 10),
    ('Match Strategy', 'Play to opponent backhand', 'Build points around pressure to the backhand side.', 2, 20),
    ('Match Strategy', 'Play to opponent forehand', 'Build points around pressure to the forehand side.', 2, 30),
    ('Match Strategy', 'Play to opponent middle/elbow', 'Use the transition point to force hesitation.', 3, 40),
    ('Match Strategy', 'Change serve strategy', 'Adjust serve selection based on opponent receive patterns.', 3, 50),
    ('Match Strategy', 'Change receive strategy', 'Adjust receive selection based on opponent serve and third-ball patterns.', 3, 60),
    ('Match Strategy', 'Pattern building', 'Use planned serve, receive, and rally patterns.', 4, 70),
    ('Match Strategy', 'Avoid repeated mistakes', 'Notice and correct repeated tactical or technical errors during a match.', 3, 80),
    ('Match Strategy', 'Score awareness', 'Make shot choices that fit the score and risk level.', 3, 90),
    ('Match Strategy', 'Play safe at 9-9 or deuce', 'Use high-percentage decisions in critical points.', 4, 100),
    ('Match Strategy', 'Take calculated risks', 'Choose aggressive options when the reward justifies the risk.', 4, 110),
    ('Match Strategy', 'Adapt during a match', 'Change tactics when the first plan stops working.', 4, 120),
    ('Match Strategy', 'Manage momentum', 'Slow down or apply pressure based on match momentum.', 3, 130),
    ('Match Strategy', 'Timeout and break strategy', 'Use breaks to reset focus and adjust tactics.', 4, 140),

    ('Mental Game', 'Pre-point routine', 'Use a repeatable routine before each point.', 2, 10),
    ('Mental Game', 'Stay calm after mistakes', 'Reset emotionally after errors instead of carrying them forward.', 2, 20),
    ('Mental Game', 'Confidence under pressure', 'Trust trained skills during close or important points.', 3, 30),
    ('Mental Game', 'Focus between points', 'Use the time between points to prepare clearly.', 2, 40),
    ('Mental Game', 'Handle losing streaks', 'Break negative runs with better routines and choices.', 3, 50),
    ('Mental Game', 'Close games', 'Finish games when leading without becoming passive.', 4, 60),
    ('Mental Game', 'Comeback mindset', 'Compete well when behind in score.', 3, 70),
    ('Mental Game', 'Play stronger opponents', 'Stay purposeful and learn while under higher pressure.', 3, 80),
    ('Mental Game', 'Play defensive opponents', 'Stay patient and avoid frustration against defensive styles.', 3, 90),
    ('Mental Game', 'Play aggressive opponents', 'Absorb pressure and disrupt attacking rhythm.', 3, 100),
    ('Mental Game', 'Manage tournament nerves', 'Prepare and perform under formal competition pressure.', 4, 110),
    ('Mental Game', 'Review match mistakes honestly', 'Reflect on matches without excuses or self-criticism spirals.', 2, 120),

    ('Fitness & Physical Readiness', 'Warm-up routine', 'Prepare body and timing before training or matches.', 1, 10),
    ('Fitness & Physical Readiness', 'Shoulder mobility', 'Maintain shoulder range and control for repeated strokes.', 2, 20),
    ('Fitness & Physical Readiness', 'Wrist and forearm conditioning', 'Build resilience for spin, serves, and flicks.', 2, 30),
    ('Fitness & Physical Readiness', 'Leg strength', 'Support low stance, explosive movement, and recovery.', 2, 40),
    ('Fitness & Physical Readiness', 'Core stability', 'Improve balance and power transfer through the trunk.', 2, 50),
    ('Fitness & Physical Readiness', 'Agility', 'Move quickly and efficiently between ball positions.', 3, 60),
    ('Fitness & Physical Readiness', 'Reaction speed', 'Improve first response to serve, receive, and fast rallies.', 3, 70),
    ('Fitness & Physical Readiness', 'Endurance', 'Maintain quality across long training sessions and matches.', 3, 80),
    ('Fitness & Physical Readiness', 'Injury prevention', 'Use habits that reduce avoidable strain and overuse injuries.', 3, 90),
    ('Fitness & Physical Readiness', 'Cool-down routine', 'Recover after play with light movement and mobility.', 1, 100),
    ('Fitness & Physical Readiness', 'Recovery habits', 'Use sleep, hydration, rest, and load management to support progress.', 2, 110)
) as seeded(category_name, skill_name, skill_description, difficulty_level, sort_order)
join public.skill_categories sc on sc.name = seeded.category_name;
