create table "public"."media" (
  "id" bigint generated by default as identity not null,
  "profile_id" bigint,
  "type" smallint not null,
  "storage_path" text,
  "thumbnail_path" text,
  "title" text,
  "description" text,
  "tags" jsonb not null default '[]'::jsonb,
  "metadata" jsonb not null default '{}'::jsonb,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."media" enable row level security;

create table "public"."comments" (
  "id" bigint generated by default as identity not null,
  "profile_id" bigint not null,
  "body" text,
  "content" jsonb,
  "metadata" jsonb not null default '{}'::jsonb,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."comments" enable row level security;

create table "public"."skill_categories" (
  "id" bigint generated by default as identity not null,
  "name" text not null,
  "description" text,
  "media_id" bigint,
  "sort_order" integer not null default 0,
  "is_active" boolean not null default true,
  "metadata" jsonb not null default '{}'::jsonb,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."skill_categories" enable row level security;

create table "public"."skills" (
  "id" bigint generated by default as identity not null,
  "category_id" bigint not null,
  "name" text not null,
  "description" text,
  "tutorial_media_id" bigint,
  "difficulty_level" smallint,
  "sort_order" integer not null default 0,
  "is_active" boolean not null default true,
  "metadata" jsonb not null default '{}'::jsonb,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."skills" enable row level security;

create table "public"."member_skill_progress" (
  "id" bigint generated by default as identity not null,
  "profile_id" bigint not null,
  "skill_id" bigint not null,
  "current_level" smallint not null default 0,
  "target_level" smallint,
  "self_rating" smallint,
  "status" text,
  "remarks" text,
  "last_practiced_at" timestamp with time zone,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."member_skill_progress" enable row level security;

create table "public"."member_skill_media" (
  "id" bigint generated by default as identity not null,
  "progress_id" bigint not null,
  "media_id" bigint not null,
  "profile_id" bigint not null,
  "caption" text,
  "practice_date" date,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."member_skill_media" enable row level security;

create table "public"."member_skill_comments" (
  "id" bigint generated by default as identity not null,
  "progress_id" bigint not null,
  "comment_id" bigint not null,
  "media_id" bigint,
  "comment_type" text,
  "created_at" timestamp with time zone not null default now()
);

alter table "public"."member_skill_comments" enable row level security;

create unique index media_pkey on public.media using btree (id);
create unique index comments_pkey on public.comments using btree (id);
create unique index skill_categories_pkey on public.skill_categories using btree (id);
create unique index skills_pkey on public.skills using btree (id);
create unique index member_skill_progress_pkey on public.member_skill_progress using btree (id);
create unique index member_skill_media_pkey on public.member_skill_media using btree (id);
create unique index member_skill_comments_pkey on public.member_skill_comments using btree (id);

create unique index member_skill_progress_profile_skill_unique
  on public.member_skill_progress using btree (profile_id, skill_id);

create index media_profile_id_idx on public.media using btree (profile_id);
create index comments_profile_id_idx on public.comments using btree (profile_id);
create index skill_categories_sort_order_idx on public.skill_categories using btree (sort_order, name);
create index skills_category_id_sort_order_idx on public.skills using btree (category_id, sort_order, name);
create index member_skill_progress_profile_id_idx on public.member_skill_progress using btree (profile_id);
create index member_skill_progress_skill_id_idx on public.member_skill_progress using btree (skill_id);
create index member_skill_media_progress_id_idx on public.member_skill_media using btree (progress_id);
create index member_skill_media_media_id_idx on public.member_skill_media using btree (media_id);
create index member_skill_comments_progress_id_idx on public.member_skill_comments using btree (progress_id);
create index member_skill_comments_comment_id_idx on public.member_skill_comments using btree (comment_id);

alter table "public"."media" add constraint "media_pkey" primary key using index "media_pkey";
alter table "public"."comments" add constraint "comments_pkey" primary key using index "comments_pkey";
alter table "public"."skill_categories" add constraint "skill_categories_pkey" primary key using index "skill_categories_pkey";
alter table "public"."skills" add constraint "skills_pkey" primary key using index "skills_pkey";
alter table "public"."member_skill_progress" add constraint "member_skill_progress_pkey" primary key using index "member_skill_progress_pkey";
alter table "public"."member_skill_media" add constraint "member_skill_media_pkey" primary key using index "member_skill_media_pkey";
alter table "public"."member_skill_comments" add constraint "member_skill_comments_pkey" primary key using index "member_skill_comments_pkey";

alter table "public"."media"
  add constraint "media_profile_id_fkey" foreign key (profile_id) references public.profiles(id) on delete set null,
  add constraint "media_type_check" check (type in (0, 1)),
  add constraint "media_tags_array_check" check (jsonb_typeof(tags) = 'array'),
  add constraint "media_metadata_object_check" check (jsonb_typeof(metadata) = 'object');

alter table "public"."comments"
  add constraint "comments_profile_id_fkey" foreign key (profile_id) references public.profiles(id) on delete cascade,
  add constraint "comments_content_object_check" check (content is null or jsonb_typeof(content) = 'object'),
  add constraint "comments_metadata_object_check" check (jsonb_typeof(metadata) = 'object');

alter table "public"."skill_categories"
  add constraint "skill_categories_media_id_fkey" foreign key (media_id) references public.media(id) on delete set null,
  add constraint "skill_categories_metadata_object_check" check (jsonb_typeof(metadata) = 'object');

alter table "public"."skills"
  add constraint "skills_category_id_fkey" foreign key (category_id) references public.skill_categories(id) on delete restrict,
  add constraint "skills_tutorial_media_id_fkey" foreign key (tutorial_media_id) references public.media(id) on delete set null,
  add constraint "skills_difficulty_level_check" check (difficulty_level is null or difficulty_level between 1 and 5),
  add constraint "skills_metadata_object_check" check (jsonb_typeof(metadata) = 'object');

alter table "public"."member_skill_progress"
  add constraint "member_skill_progress_profile_id_fkey" foreign key (profile_id) references public.profiles(id) on delete cascade,
  add constraint "member_skill_progress_skill_id_fkey" foreign key (skill_id) references public.skills(id) on delete cascade,
  add constraint "member_skill_progress_profile_skill_unique" unique using index "member_skill_progress_profile_skill_unique",
  add constraint "member_skill_progress_current_level_check" check (current_level between 0 and 5),
  add constraint "member_skill_progress_target_level_check" check (target_level is null or target_level between 0 and 5),
  add constraint "member_skill_progress_self_rating_check" check (self_rating is null or self_rating between 1 and 10);

alter table "public"."member_skill_media"
  add constraint "member_skill_media_progress_id_fkey" foreign key (progress_id) references public.member_skill_progress(id) on delete cascade,
  add constraint "member_skill_media_media_id_fkey" foreign key (media_id) references public.media(id) on delete cascade,
  add constraint "member_skill_media_profile_id_fkey" foreign key (profile_id) references public.profiles(id) on delete cascade;

alter table "public"."member_skill_comments"
  add constraint "member_skill_comments_progress_id_fkey" foreign key (progress_id) references public.member_skill_progress(id) on delete cascade,
  add constraint "member_skill_comments_comment_id_fkey" foreign key (comment_id) references public.comments(id) on delete cascade,
  add constraint "member_skill_comments_media_id_fkey" foreign key (media_id) references public.media(id) on delete set null,
  add constraint "member_skill_comments_comment_type_check" check (
    comment_type is null
    or comment_type in ('self_note', 'coach_feedback', 'peer_comment', 'system_note')
  );

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create trigger set_media_updated_at
before update on public.media
for each row execute function public.set_updated_at();

create trigger set_comments_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

create trigger set_skill_categories_updated_at
before update on public.skill_categories
for each row execute function public.set_updated_at();

create trigger set_skills_updated_at
before update on public.skills
for each row execute function public.set_updated_at();

create trigger set_member_skill_progress_updated_at
before update on public.member_skill_progress
for each row execute function public.set_updated_at();

create trigger set_member_skill_media_updated_at
before update on public.member_skill_media
for each row execute function public.set_updated_at();

grant select on table "public"."media" to "authenticated";
grant insert on table "public"."media" to "authenticated";
grant update on table "public"."media" to "authenticated";
grant delete on table "public"."media" to "authenticated";
grant select on table "public"."media" to "service_role";
grant insert on table "public"."media" to "service_role";
grant update on table "public"."media" to "service_role";
grant delete on table "public"."media" to "service_role";

grant select on table "public"."comments" to "authenticated";
grant insert on table "public"."comments" to "authenticated";
grant update on table "public"."comments" to "authenticated";
grant delete on table "public"."comments" to "authenticated";
grant select on table "public"."comments" to "service_role";
grant insert on table "public"."comments" to "service_role";
grant update on table "public"."comments" to "service_role";
grant delete on table "public"."comments" to "service_role";

grant select on table "public"."skill_categories" to "authenticated";
grant select on table "public"."skill_categories" to "service_role";
grant insert on table "public"."skill_categories" to "service_role";
grant update on table "public"."skill_categories" to "service_role";
grant delete on table "public"."skill_categories" to "service_role";

grant select on table "public"."skills" to "authenticated";
grant select on table "public"."skills" to "service_role";
grant insert on table "public"."skills" to "service_role";
grant update on table "public"."skills" to "service_role";
grant delete on table "public"."skills" to "service_role";

grant select on table "public"."member_skill_progress" to "authenticated";
grant insert on table "public"."member_skill_progress" to "authenticated";
grant update on table "public"."member_skill_progress" to "authenticated";
grant delete on table "public"."member_skill_progress" to "authenticated";
grant select on table "public"."member_skill_progress" to "service_role";
grant insert on table "public"."member_skill_progress" to "service_role";
grant update on table "public"."member_skill_progress" to "service_role";
grant delete on table "public"."member_skill_progress" to "service_role";

grant select on table "public"."member_skill_media" to "authenticated";
grant insert on table "public"."member_skill_media" to "authenticated";
grant update on table "public"."member_skill_media" to "authenticated";
grant delete on table "public"."member_skill_media" to "authenticated";
grant select on table "public"."member_skill_media" to "service_role";
grant insert on table "public"."member_skill_media" to "service_role";
grant update on table "public"."member_skill_media" to "service_role";
grant delete on table "public"."member_skill_media" to "service_role";

grant select on table "public"."member_skill_comments" to "authenticated";
grant insert on table "public"."member_skill_comments" to "authenticated";
grant update on table "public"."member_skill_comments" to "authenticated";
grant delete on table "public"."member_skill_comments" to "authenticated";
grant select on table "public"."member_skill_comments" to "service_role";
grant insert on table "public"."member_skill_comments" to "service_role";
grant update on table "public"."member_skill_comments" to "service_role";
grant delete on table "public"."member_skill_comments" to "service_role";

create policy "Authenticated users can read active skill categories"
on "public"."skill_categories"
as permissive
for select
to authenticated
using (is_active = true);

create policy "Authenticated users can read active skills"
on "public"."skills"
as permissive
for select
to authenticated
using (
  is_active = true
  and exists (
    select 1
    from public.skill_categories sc
    where sc.id = skills.category_id
      and sc.is_active = true
  )
);

create policy "Users can read reusable and own media"
on "public"."media"
as permissive
for select
to authenticated
using (
  profile_id is null
  or exists (
    select 1
    from public.profiles p
    where p.id = media.profile_id
      and p.auth_user_id = auth.uid()
  )
  or exists (
    select 1
    from public.member_skill_media msm
    join public.member_skill_progress msp on msp.id = msm.progress_id
    join public.profiles p on p.id = msp.profile_id
    where msm.media_id = media.id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can create own media"
on "public"."media"
as permissive
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = media.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can update own media"
on "public"."media"
as permissive
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = media.profile_id
      and p.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = media.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can delete own media"
on "public"."media"
as permissive
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = media.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can read relevant comments"
on "public"."comments"
as permissive
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = comments.profile_id
      and p.auth_user_id = auth.uid()
  )
  or exists (
    select 1
    from public.member_skill_comments msc
    join public.member_skill_progress msp on msp.id = msc.progress_id
    join public.profiles p on p.id = msp.profile_id
    where msc.comment_id = comments.id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can create own comments"
on "public"."comments"
as permissive
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = comments.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can update own comments"
on "public"."comments"
as permissive
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = comments.profile_id
      and p.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = comments.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can delete own comments"
on "public"."comments"
as permissive
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = comments.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can read own skill progress"
on "public"."member_skill_progress"
as permissive
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = member_skill_progress.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can create own skill progress"
on "public"."member_skill_progress"
as permissive
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = member_skill_progress.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can update own skill progress"
on "public"."member_skill_progress"
as permissive
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = member_skill_progress.profile_id
      and p.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = member_skill_progress.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can delete own skill progress"
on "public"."member_skill_progress"
as permissive
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = member_skill_progress.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can read own skill media links"
on "public"."member_skill_media"
as permissive
for select
to authenticated
using (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_media.progress_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can create own skill media links"
on "public"."member_skill_media"
as permissive
for insert
to authenticated
with check (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_media.progress_id
      and msp.profile_id = member_skill_media.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can update own skill media links"
on "public"."member_skill_media"
as permissive
for update
to authenticated
using (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_media.progress_id
      and p.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_media.progress_id
      and msp.profile_id = member_skill_media.profile_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can delete own skill media links"
on "public"."member_skill_media"
as permissive
for delete
to authenticated
using (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_media.progress_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can read own skill comment links"
on "public"."member_skill_comments"
as permissive
for select
to authenticated
using (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_comments.progress_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can create own skill comment links"
on "public"."member_skill_comments"
as permissive
for insert
to authenticated
with check (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles owner_profile on owner_profile.id = msp.profile_id
    join public.comments c on c.id = member_skill_comments.comment_id
    join public.profiles commenter_profile on commenter_profile.id = c.profile_id
    where msp.id = member_skill_comments.progress_id
      and owner_profile.auth_user_id = auth.uid()
      and commenter_profile.auth_user_id = auth.uid()
  )
);

create policy "Users can update own skill comment links"
on "public"."member_skill_comments"
as permissive
for update
to authenticated
using (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_comments.progress_id
      and p.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_comments.progress_id
      and p.auth_user_id = auth.uid()
  )
);

create policy "Users can delete own skill comment links"
on "public"."member_skill_comments"
as permissive
for delete
to authenticated
using (
  exists (
    select 1
    from public.member_skill_progress msp
    join public.profiles p on p.id = msp.profile_id
    where msp.id = member_skill_comments.progress_id
      and p.auth_user_id = auth.uid()
  )
);

comment on table public.media is 'Reusable photo/video records for tutorials, player uploads, and future app features.';
comment on column public.media.type is '0 = image, 1 = video.';
comment on column public.media.storage_path is 'Supabase Storage path or external media location.';
comment on column public.comments.content is 'Rich comment payload. Keep body populated for plain-text preview/search when possible.';
comment on table public.skill_categories is 'Configurable table tennis skill ladder categories such as Serve, Forehand, Backhand, and Mental Game.';
comment on table public.skills is 'Individual skill ladder items under each category.';
comment on table public.member_skill_progress is 'One progress row per profile and skill.';
comment on column public.member_skill_progress.current_level is '0 Not Started, 1 Learning, 2 Practice Ready, 3 Match Ready, 4 Reliable Under Pressure, 5 Advanced / Weapon.';
comment on table public.member_skill_media is 'Links member practice media to a skill progress row.';
comment on table public.member_skill_comments is 'Links notes and coach/player comments to a member skill progress row, optionally for a specific media item.';
